#.rubocop.yml
require: rubocop-rspec
inherit_from: .rubocop_todo.yml
AllCops:
  Rails:
    Enabled: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Gemfile'
    - 'Guardfile'
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
